import 'package:flutter/material.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedHandshelpingWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedPluscircleWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedSHAREWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedDONATEWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedVectorWidget14.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedSplash_batterythreequartersWidget2.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedCONTRIBUTEWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedVectorWidget15.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedVectorWidget9.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedVectorWidget10.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedSharealtWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedSplash_wifiWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedSplash_signalWidget2.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/Generated1256Widget2.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedSQUIRRELWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedVectorWidget13.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedMoneycheckaltWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedCREATEGAMEWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash6widget/generated/GeneratedVectorWidget11.dart';

/* Frame splash6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplash6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: Container(
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(63, 0, 0, 0),
              offset: Offset(0.0, 4.0),
              blurRadius: 4.0,
            )
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            width: 375.0,
            height: 812.0,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment(-1.0000000031316771, -1.0258620676630277),
                end: Alignment(1.034666676823646, 1.0061576104933487),
                stops: [0.0, 1.0],
                colors: [
                  Color.fromARGB(73, 255, 200, 6),
                  Color.fromARGB(89, 251, 59, 163)
                ],
              ),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 21.478872299194336,
                    height: null,
                    child: TransformHelper.translate(
                        x: 157.76,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.013225906588173852;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  10.739436149597168;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.014431431962938732,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget9())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 406.395263671875,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_batterythreequartersWidget2(),
                  ),
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 17.18309783935547,
                    height: null,
                    child: TransformHelper.translate(
                        x: 116.09,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.01587108908028438;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  12.887324333190918;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.013373351449449662,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget10())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 406.395263671875,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_wifiWidget2(),
                  ),
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 18.042253494262695,
                    height: null,
                    child: TransformHelper.translate(
                        x: 135.42,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.016929161372443137;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  13.746479034423828;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.012315270935960592,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget11())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 406.395263671875,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_signalWidget2(),
                  ),
                  Positioned(
                    left: 20.0,
                    top: 7.0,
                    right: null,
                    bottom: null,
                    width: 75.0,
                    height: 22.0,
                    child: Generated1256Widget2(),
                  ),
                  Positioned(
                    left: -193.0,
                    top: -182.49996948242188,
                    right: null,
                    bottom: null,
                    width: 485.2388916015625,
                    height: 412.147705078125,
                    child: GeneratedEllipse1Widget2(),
                  ),
                  Positioned(
                    left: 144.76092529296875,
                    top: 565.2037353515625,
                    right: null,
                    bottom: null,
                    width: 433.9779357910156,
                    height: 430.59173583984375,
                    child: GeneratedEllipse2Widget2(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: null,
                    bottom: null,
                    width: 240.0,
                    height: 812.0,
                    child: GeneratedRectangle1Widget(),
                  ),
                  Positioned(
                    left: 10.0,
                    top: 10.0,
                    right: null,
                    bottom: null,
                    width: 245.0,
                    height: 45.0,
                    child: GeneratedSQUIRRELWidget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 60.0,
                    right: null,
                    bottom: null,
                    width: 240.0,
                    height: 40.0,
                    child: GeneratedRectangle2Widget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 110.0,
                    right: null,
                    bottom: null,
                    width: 240.0,
                    height: 40.0,
                    child: GeneratedRectangle3Widget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 165.0,
                    right: null,
                    bottom: null,
                    width: 240.0,
                    height: 40.0,
                    child: GeneratedRectangle4Widget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 220.0,
                    right: null,
                    bottom: null,
                    width: 240.0,
                    height: 40.0,
                    child: GeneratedRectangle5Widget(),
                  ),
                  Positioned(
                    left: 40.0,
                    top: 65.0,
                    right: null,
                    bottom: null,
                    width: 205.0,
                    height: 32.0,
                    child: GeneratedCREATEGAMEWidget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.06458333333333334;
                      double scaleX =
                          (constraints.maxWidth * percentWidth) / 24.21875;

                      double percentHeight = 0.029826046798029558;
                      double scaleY =
                          (constraints.maxHeight * percentHeight) / 24.21875;

                      return Stack(children: [
                        TransformHelper.translateAndScale(
                            translateX: constraints.maxWidth * 0.016,
                            translateY:
                                constraints.maxHeight * 0.0874384236453202,
                            translateZ: 0,
                            scaleX: scaleX,
                            scaleY: scaleY,
                            scaleZ: 1,
                            child: GeneratedVectorWidget12())
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.06666666666666667;
                      double scaleX =
                          (constraints.maxWidth * percentWidth) / 25.0;

                      double percentHeight = 0.021551724137931036;
                      double scaleY =
                          (constraints.maxHeight * percentHeight) / 17.5;

                      return Stack(children: [
                        TransformHelper.translateAndScale(
                            translateX:
                                constraints.maxWidth * 0.018666666666666668,
                            translateY:
                                constraints.maxHeight * 0.21674876847290642,
                            translateZ: 0,
                            scaleX: scaleX,
                            scaleY: scaleY,
                            scaleZ: 1,
                            child: GeneratedVectorWidget13())
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 40.0,
                    top: 168.0,
                    right: null,
                    bottom: null,
                    width: 135.0,
                    height: 18.0,
                    child: GeneratedDONATEWidget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.06666678873697916;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          25.000045776367188;

                      double percentHeight = 0.02462846070087602;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          19.998310089111328;

                      return Stack(children: [
                        TransformHelper.translateAndScale(
                            translateX:
                                constraints.maxWidth * 0.02666666666666667,
                            translateY:
                                constraints.maxHeight * 0.1477832512315271,
                            translateZ: 0,
                            scaleX: scaleX,
                            scaleY: scaleY,
                            scaleZ: 1,
                            child: GeneratedVectorWidget14())
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 43.0,
                    top: 116.0,
                    right: null,
                    bottom: null,
                    width: 175.0,
                    height: 35.0,
                    child: GeneratedCONTRIBUTEWidget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.058333333333333334;
                      double scaleX =
                          (constraints.maxWidth * percentWidth) / 21.875;

                      double percentHeight = 0.03078817733990148;
                      double scaleY =
                          (constraints.maxHeight * percentHeight) / 25.0;

                      return Stack(children: [
                        TransformHelper.translateAndScale(
                            translateX:
                                constraints.maxWidth * 0.02666666666666667,
                            translateY:
                                constraints.maxHeight * 0.28078817733990147,
                            translateZ: 0,
                            scaleX: scaleX,
                            scaleY: scaleY,
                            scaleZ: 1,
                            child: GeneratedVectorWidget15())
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 45.0,
                    top: 224.0,
                    right: null,
                    bottom: null,
                    width: 125.0,
                    height: 25.0,
                    child: GeneratedSHAREWidget(),
                  ),
                  Positioned(
                    left: 200.693115234375,
                    top: 451.92303466796875,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedPluscircleWidget(),
                  ),
                  Positioned(
                    left: -104.6724853515625,
                    top: 506.6153869628906,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedMoneycheckaltWidget(),
                  ),
                  Positioned(
                    left: -104.6724853515625,
                    top: 506.6153869628906,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedHandshelpingWidget(),
                  ),
                  Positioned(
                    left: -104.6724853515625,
                    top: 506.6153869628906,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSharealtWidget(),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
