import 'package:flutter/material.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedVectorWidget17.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedSalaryoffersConceptWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedSplash_signalWidget3.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedPROBLEMYouarebeingonebyonetoldfirstMsalarypackagesoutof.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedVectorWidget19.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedSplash_wifiWidget3.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedVectorWidget20.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/Generated1256Widget3.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedEllipse2Widget3.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedVectorWidget18.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedEllipse1Widget3.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedVectorWidget16.dart';
import 'package:flutterapp/squirrelapp/generatedsplash5widget/generated/GeneratedSplash_batterythreequartersWidget3.dart';

/* Frame splash5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplash5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: Container(
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(63, 0, 0, 0),
              offset: Offset(0.0, 4.0),
              blurRadius: 4.0,
            )
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            width: 375.0,
            height: 812.0,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment(-1.0000000031316771, -1.0258620676630277),
                end: Alignment(1.034666676823646, 1.0061576104933487),
                stops: [0.0, 1.0],
                colors: [
                  Color.fromARGB(73, 255, 200, 6),
                  Color.fromARGB(89, 251, 59, 163)
                ],
              ),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 21.478872299194336,
                    height: null,
                    child: TransformHelper.translate(
                        x: 157.76,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.013225906588173852;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  10.739436149597168;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.014431431962938732,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget16())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 406.395263671875,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_batterythreequartersWidget3(),
                  ),
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 17.18309783935547,
                    height: null,
                    child: TransformHelper.translate(
                        x: 116.09,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.01587108908028438;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  12.887324333190918;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.013373351449449662,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget17())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 406.395263671875,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_wifiWidget3(),
                  ),
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 18.042253494262695,
                    height: null,
                    child: TransformHelper.translate(
                        x: 135.42,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.016929161372443137;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  13.746479034423828;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.012315270935960592,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget18())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 406.395263671875,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_signalWidget3(),
                  ),
                  Positioned(
                    left: 20.0,
                    top: 7.0,
                    right: null,
                    bottom: null,
                    width: 75.0,
                    height: 22.0,
                    child: Generated1256Widget3(),
                  ),
                  Positioned(
                    left: -193.0,
                    top: -182.49996948242188,
                    right: null,
                    bottom: null,
                    width: 485.2388916015625,
                    height: 412.147705078125,
                    child: GeneratedEllipse1Widget3(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.058333333333333334;
                      double scaleX =
                          (constraints.maxWidth * percentWidth) / 21.875;

                      double percentHeight = 0.02693965517241379;
                      double scaleY =
                          (constraints.maxHeight * percentHeight) / 21.875;

                      return Stack(children: [
                        TransformHelper.translateAndScale(
                            translateX:
                                constraints.maxWidth * 0.02666666666666667,
                            translateY:
                                constraints.maxHeight * 0.03694581280788178,
                            translateZ: 0,
                            scaleX: scaleX,
                            scaleY: scaleY,
                            scaleZ: 1,
                            child: GeneratedVectorWidget19())
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 144.76092529296875,
                    top: 565.2037353515625,
                    right: null,
                    bottom: null,
                    width: 433.9779357910156,
                    height: 430.59173583984375,
                    child: GeneratedEllipse2Widget3(),
                  ),
                  Positioned(
                    left: 43.0,
                    top: 24.0,
                    right: null,
                    bottom: null,
                    width: 254.0,
                    height: 22.0,
                    child: GeneratedSalaryoffersConceptWidget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.06458333333333334;
                      double scaleX =
                          (constraints.maxWidth * percentWidth) / 24.21875;

                      double percentHeight = 0.029826046798029558;
                      double scaleY =
                          (constraints.maxHeight * percentHeight) / 24.21875;

                      return Stack(children: [
                        TransformHelper.translateAndScale(
                            translateX:
                                constraints.maxWidth * 0.8693333333333333,
                            translateY:
                                constraints.maxHeight * 0.04187192118226601,
                            translateZ: 0,
                            scaleX: scaleX,
                            scaleY: scaleY,
                            scaleZ: 1,
                            child: GeneratedVectorWidget20())
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 21.0,
                    top: 68.0,
                    right: null,
                    bottom: null,
                    width: 331.0,
                    height: 733.0,
                    child:
                        GeneratedPROBLEMYouarebeingonebyonetoldfirstMsalarypackagesoutof(),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
