import 'package:flutter/material.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedVectorWidget36.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedEllipse18Widget4.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedSplash_wifiWidget7.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedIfyouacceptyougetthissalarypackageandgameendsIfyourejec2.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedVectorWidget38.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedEllipse2Widget7.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedInfocircleWidget3.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedSplash_batterythreequartersWidget7.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedSplash_signalWidget7.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/Generated1256Widget7.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedPackage8inlakhsWidget.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedACCEPTWidget2.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedEllipse19Widget3.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedEllipse1Widget7.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedREJECTWidget2.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/Generated70Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedVectorWidget40.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedSalaryoffersWidget4.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedVectorWidget37.dart';
import 'package:flutterapp/squirrelapp/generatedsplash8widget/generated/GeneratedVectorWidget39.dart';

/* Frame splash8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplash8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.800000011920929,
      child: Container(
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(63, 0, 0, 0),
              offset: Offset(0.0, 4.0),
              blurRadius: 4.0,
            )
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            width: 375.0,
            height: 812.0,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment(-1.0000000031316771, -1.0258620676630277),
                end: Alignment(1.034666676823646, 1.0061576104933487),
                stops: [0.0, 1.0],
                colors: [
                  Color.fromARGB(73, 255, 200, 6),
                  Color.fromARGB(89, 251, 59, 163)
                ],
              ),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 21.478872299194336,
                    height: null,
                    child: TransformHelper.translate(
                        x: 157.76,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.013225906588173852;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  10.739436149597168;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.014431431962938732,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget36())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 450.0,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_batterythreequartersWidget7(),
                  ),
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 17.18309783935547,
                    height: null,
                    child: TransformHelper.translate(
                        x: 116.09,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.01587108908028438;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  12.887324333190918;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.013373351449449662,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget37())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 450.0,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_wifiWidget7(),
                  ),
                  Positioned(
                    left: null,
                    top: 0.0,
                    right: null,
                    bottom: 0.0,
                    width: 18.042253494262695,
                    height: null,
                    child: TransformHelper.translate(
                        x: 135.42,
                        y: 0.00,
                        z: 0,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentHeight = 0.016929161372443137;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  13.746479034423828;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: constraints.maxHeight *
                                    0.012315270935960592,
                                translateZ: 0,
                                scaleX: 1,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget38())
                          ]);
                        })),
                  ),
                  Positioned(
                    left: 188.0,
                    top: 450.0,
                    right: null,
                    bottom: null,
                    width: 25.0,
                    height: 25.0,
                    child: GeneratedSplash_signalWidget7(),
                  ),
                  Positioned(
                    left: 20.0,
                    top: 7.0,
                    right: null,
                    bottom: null,
                    width: 75.0,
                    height: 22.0,
                    child: Generated1256Widget7(),
                  ),
                  Positioned(
                    left: -193.0,
                    top: -182.49996948242188,
                    right: null,
                    bottom: null,
                    width: 485.2388916015625,
                    height: 412.147705078125,
                    child: GeneratedEllipse1Widget7(),
                  ),
                  Positioned(
                    left: 47.0,
                    top: 25.0,
                    right: null,
                    bottom: null,
                    width: 215.0,
                    height: 22.0,
                    child: GeneratedSalaryoffersWidget4(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.058333333333333334;
                      double scaleX =
                          (constraints.maxWidth * percentWidth) / 21.875;

                      double percentHeight = 0.02693965517241379;
                      double scaleY =
                          (constraints.maxHeight * percentHeight) / 21.875;

                      return Stack(children: [
                        TransformHelper.translateAndScale(
                            translateX:
                                constraints.maxWidth * 0.02666666666666667,
                            translateY:
                                constraints.maxHeight * 0.03694581280788178,
                            translateZ: 0,
                            scaleX: scaleX,
                            scaleY: scaleY,
                            scaleZ: 1,
                            child: GeneratedVectorWidget39())
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 144.76092529296875,
                    top: 565.2037353515625,
                    right: null,
                    bottom: null,
                    width: 433.9779357910156,
                    height: 430.59173583984375,
                    child: GeneratedEllipse2Widget7(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.06458333333333334;
                      double scaleX =
                          (constraints.maxWidth * percentWidth) / 24.21875;

                      double percentHeight = 0.029826046798029558;
                      double scaleY =
                          (constraints.maxHeight * percentHeight) / 24.21875;

                      return Stack(children: [
                        TransformHelper.translateAndScale(
                            translateX: constraints.maxWidth * 0.88,
                            translateY:
                                constraints.maxHeight * 0.04310344827586207,
                            translateZ: 0,
                            scaleX: scaleX,
                            scaleY: scaleY,
                            scaleZ: 1,
                            child: GeneratedVectorWidget40())
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 70.0,
                    top: 290.0,
                    right: null,
                    bottom: null,
                    width: 227.0,
                    height: 129.0,
                    child: Generated70Widget1(),
                  ),
                  Positioned(
                    left: 80.0,
                    top: 520.0,
                    right: null,
                    bottom: null,
                    width: 195.0,
                    height: 85.0,
                    child: GeneratedACCEPTWidget2(),
                  ),
                  Positioned(
                    left: 80.0,
                    top: 620.0,
                    right: null,
                    bottom: null,
                    width: 195.0,
                    height: 65.0,
                    child: GeneratedREJECTWidget2(),
                  ),
                  Positioned(
                    left: 136.0,
                    top: 338.0,
                    right: null,
                    bottom: null,
                    width: 142.0,
                    height: 63.0,
                    child: GeneratedInfocircleWidget3(),
                  ),
                  Positioned(
                    left: 55.0,
                    top: 218.0,
                    right: null,
                    bottom: null,
                    width: 256.0,
                    height: 72.0,
                    child: GeneratedPackage8inlakhsWidget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 70.0,
                    right: null,
                    bottom: null,
                    width: 377.0,
                    height: 102.0,
                    child:
                        GeneratedIfyouacceptyougetthissalarypackageandgameendsIfyourejec2(),
                  ),
                  Positioned(
                    left: 50.0,
                    top: 505.0,
                    right: null,
                    bottom: null,
                    width: 250.0,
                    height: 75.0,
                    child: GeneratedEllipse18Widget4(),
                  ),
                  Positioned(
                    left: 55.0,
                    top: 610.0,
                    right: null,
                    bottom: null,
                    width: 250.0,
                    height: 75.0,
                    child: GeneratedEllipse19Widget3(),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
